### ISSUE TITLE
NIST and ENT test

### ISSUE THREAD

**Issue by kaventre** [mattix1710/TRNG_ImageSampling#1]
How can I use this project to generate binaries for NIST and ENT tests,？I looked at the tests that have these two test suites in the paper, but I can't reproduce the experimental results in the paper after converting out to binaries.

**Comment by mattix1710** [comment]
Random binary values are created by using algorithm described in the article mentioned in **References** tab in main README file.

If you are interested strictly on using generated binaries, you can analyze sections **Image capturing**, **PRE-PROCESSING**, **POST-PROCESSING** and **POST-PROCESSING main loop** in Jupyter notebook file.
